parameters:
  connection.factory.phongo.name: 'phongo'
  database.factory.phongo.name: 'mongo'

services:
  connection.factory.phongo:
    class: Vain\Mongo\Connection\Factory\PhongoConnectionFactory
    arguments: ['%connection.factory.phongo.name%']
    tags:
      - {name: connection.factory}
  database.factory.phongo:
    class: Vain\Mongo\Database\Factory\PhongoDatabaseFactory
    arguments: ['%database.factory.phongo.name%']
    tags:
      - {name: database.factory}
  collection.key.storage:
    class: Vain\Mongo\Collection\Key\Storage\CollectionKeyStorage
  collection.operation.factory.phongo:
    parent: operation.factory.abstract
    class: Vain\Mongo\Operation\Factory\CollectionOperationFactory
    arguments: ['@database.document', '@collection.key.storage']
  collection.operation.factory: '@collection.operation.factory.phongo'