parameters:
  connection.factory.phongo.name: 'mongo'
  database.factory.phongo.name: 'document'

services:
  connection.factory.phongo:
    class: Vain\Mongo\Connection\Factory\PhongoConnectionFactory
    arguments: ['%connection.factory.phongo.name%']
    tags:
      - {name: connection.factory}
  database.factory.phongo:
    class: Vain\Mongo\Database\Factory\PhongoDatabaseFactory
    arguments: ['%database.factory.phongo.name%']
    tags:
      - {name: database.factory}
  collection.key.generator.storage:
    class: Vain\Mongo\Collection\Key\Generator\Storage\CollectionKeyGeneratorStorage
  collection.operation.factory.phongo:
    class: Vain\Mongo\Operation\Factory\CollectionOperationFactory
    arguments: ['@database.document', '@collection.key.generator.storage']