parameters:
  connection.phongo.name: 'phongo'
  database.factory.phongo.name: 'mongo'
  database.document.name: 'document'

services:
  database.document:
    class: Vain\Mongo\Database\PhongoDatabase
    arguments: ['@connection.phongo']
  connection.phongo:
    parent: connection.abstract
    class: Vain\Mongo\Connection\PhongoConnection
    arguments: ['%connection.phongo.name%']
  document.operation.factory.phongo:
    parent: operation.factory.abstract
    class: Vain\Mongo\Document\Operation\Factory\DocumentOperationFactory
    arguments: ['@database.document']
  document.operation.factory: '@document.operation.factory.phongo'
  document.collection.abstract:
    abstract: true
    arguments: ['@counter']
  connection.factory.phongo.proxy:
    class: Vain\Core\Connection\Factory\Decorator\Proxy\ConnectionFactoryProxyDecorator
    decorates: connection.factory.phongo
    decoration_priority: 100
    arguments: ['@connection.factory.phongo.proxy.inner']