parameters:
  connection.factory.phongo.name: 'phongo'
  database.factory.phongo.name: 'mongo'

services:
  connection.factory.phongo:
    class: Vain\Mongo\Connection\Factory\PhongoConnectionFactory
    arguments: ['%connection.factory.phongo.name%']
    tags:
      - {name: connection.factory}
  database.factory.phongo:
    class: Vain\Mongo\Database\Factory\PhongoDatabaseFactory
    arguments: ['%database.factory.phongo.name%']
    tags:
      - {name: database.factory}
  document.operation.factory.phongo:
    parent: operation.factory.abstract
    class: Vain\Mongo\Document\Operation\Factory\DocumentOperationFactory
    arguments: ['@database.document']
  document.operation.factory: '@document.operation.factory.phongo'
  document.collection.abstract:
    abstract: true
    arguments: ['@counter']